all: configure

.PHONY: configure

configure:
	ln -sf `pwd`/../system/cat `pwd`/fs/; \
	ln -sf `pwd`/../system/init `pwd`/fs/; \
	ln -sf `pwd`/../system/ls `pwd`/fs/; \
	ln -sf `pwd`/../system/mkdir `pwd`/fs/; \
	ln -sf `pwd`/../system/sh `pwd`/fs/; \
	ln -sf `pwd`/../system/test2 `pwd`/fs/; \
	ln -sf `pwd`/../../tests/gfx_tests/mandelbrot `pwd`/fs/; \
	ln -sf `pwd`/../system/clear `pwd`/fs/; 
