int _inp_0(){__asm("\tin.r.p re 0");}
int _inp_1(){__asm("\tin.r.p re 1");}
int _inp_2(){__asm("\tin.r.p re 2");}
int _inp_3(){__asm("\tin.r.p re 3");}
int _inp_4(){__asm("\tin.r.p re 4");}
int _inp_5(){__asm("\tin.r.p re 5");}
int _inp_6(){__asm("\tin.r.p re 6");}
int _inp_7(){__asm("\tin.r.p re 7");}
int _inp_8(){__asm("\tin.r.p re 8");}
int _inp_9(){__asm("\tin.r.p re 9");}
int _inp_10(){__asm("\tin.r.p re 10");}
int _inp_11(){__asm("\tin.r.p re 11");}
int _inp_12(){__asm("\tin.r.p re 12");}
int _inp_13(){__asm("\tin.r.p re 13");}
int _inp_14(){__asm("\tin.r.p re 14");}
int _inp_15(){__asm("\tin.r.p re 15");}
int _inp_16(){__asm("\tin.r.p re 16");}
int _inp_17(){__asm("\tin.r.p re 17");}
int _inp_18(){__asm("\tin.r.p re 18");}
