unsigned int _inp__led_port(void);
unsigned int _inp_0(void);
void _outp__led_port(__reg("ra") unsigned int val);
void _outp_0(__reg("ra") unsigned int val);
unsigned int _inp__serial_data_in_port(void);
unsigned int _inp__serial_next_port(void);
unsigned int _inp_1(void);
void _outp__serial_data_in_port(__reg("ra") unsigned int val);
void _outp__serial_next_port(__reg("ra") unsigned int val);
void _outp_1(__reg("ra") unsigned int val);
unsigned int _inp__serial_in_waiting_port(void);
unsigned int _inp_2(void);
void _outp__serial_in_waiting_port(__reg("ra") unsigned int val);
void _outp_2(__reg("ra") unsigned int val);
unsigned int _inp__serial_data_out_port(void);
unsigned int _inp_3(void);
void _outp__serial_data_out_port(__reg("ra") unsigned int val);
void _outp_3(__reg("ra") unsigned int val);
unsigned int _inp__serial_tx_busy_port(void);
unsigned int _inp_4(void);
void _outp__serial_tx_busy_port(__reg("ra") unsigned int val);
void _outp_4(__reg("ra") unsigned int val);
unsigned int _inp__text_addr_port(void);
unsigned int _inp_5(void);
void _outp__text_addr_port(__reg("ra") unsigned int val);
void _outp_5(__reg("ra") unsigned int val);
unsigned int _inp__text_data_port(void);
unsigned int _inp_6(void);
void _outp__text_data_port(__reg("ra") unsigned int val);
void _outp_6(__reg("ra") unsigned int val);
unsigned int _inp__key_data_in_port(void);
unsigned int _inp__key_next_port(void);
unsigned int _inp_7(void);
void _outp__key_data_in_port(__reg("ra") unsigned int val);
void _outp__key_next_port(__reg("ra") unsigned int val);
void _outp_7(__reg("ra") unsigned int val);
unsigned int _inp__key_in_waiting_port(void);
unsigned int _inp_8(void);
void _outp__key_in_waiting_port(__reg("ra") unsigned int val);
void _outp_8(__reg("ra") unsigned int val);
unsigned int _inp__gfx_addr_port(void);
unsigned int _inp_9(void);
void _outp__gfx_addr_port(__reg("ra") unsigned int val);
void _outp_9(__reg("ra") unsigned int val);
unsigned int _inp__gfx_data_port(void);
unsigned int _inp_10(void);
void _outp__gfx_data_port(__reg("ra") unsigned int val);
void _outp_10(__reg("ra") unsigned int val);
unsigned int _inp__sound_freq_port(void);
unsigned int _inp_11(void);
void _outp__sound_freq_port(__reg("ra") unsigned int val);
void _outp_11(__reg("ra") unsigned int val);
unsigned int _inp__gfx_screen_en_port(void);
unsigned int _inp_12(void);
void _outp__gfx_screen_en_port(__reg("ra") unsigned int val);
void _outp_12(__reg("ra") unsigned int val);
unsigned int _inp__disk_busy_port(void);
unsigned int _inp__disk_reset_port(void);
unsigned int _inp_13(void);
void _outp__disk_busy_port(__reg("ra") unsigned int val);
void _outp__disk_reset_port(__reg("ra") unsigned int val);
void _outp_13(__reg("ra") unsigned int val);
unsigned int _inp__disk_error_port(void);
unsigned int _inp__disk_block_addr_port(void);
unsigned int _inp_14(void);
void _outp__disk_error_port(__reg("ra") unsigned int val);
void _outp__disk_block_addr_port(__reg("ra") unsigned int val);
void _outp_14(__reg("ra") unsigned int val);
unsigned int _inp__disk_data_in_port(void);
unsigned int _inp__disk_data_in_next_port(void);
unsigned int _inp_15(void);
void _outp__disk_data_in_port(__reg("ra") unsigned int val);
void _outp__disk_data_in_next_port(__reg("ra") unsigned int val);
void _outp_15(__reg("ra") unsigned int val);
unsigned int _inp__disk_data_in_rd_en_port(void);
unsigned int _inp__disk_data_in_addr_port(void);
unsigned int _inp_16(void);
void _outp__disk_data_in_rd_en_port(__reg("ra") unsigned int val);
void _outp__disk_data_in_addr_port(__reg("ra") unsigned int val);
void _outp_16(__reg("ra") unsigned int val);
unsigned int _inp__disk_data_out_port(void);
unsigned int _inp_17(void);
void _outp__disk_data_out_port(__reg("ra") unsigned int val);
void _outp_17(__reg("ra") unsigned int val);
unsigned int _inp__disk_data_out_wr_en_port(void);
unsigned int _inp__disk_data_out_addr_port(void);
unsigned int _inp_18(void);
void _outp__disk_data_out_wr_en_port(__reg("ra") unsigned int val);
void _outp__disk_data_out_addr_port(__reg("ra") unsigned int val);
void _outp_18(__reg("ra") unsigned int val);
unsigned int _inp_19(void);
void _outp_19(__reg("ra") unsigned int val);
unsigned int _inp_20(void);
void _outp_20(__reg("ra") unsigned int val);
unsigned int _inp_21(void);
void _outp_21(__reg("ra") unsigned int val);
unsigned int _inp_22(void);
void _outp_22(__reg("ra") unsigned int val);
unsigned int _inp_23(void);
void _outp_23(__reg("ra") unsigned int val);
unsigned int _inp_24(void);
void _outp_24(__reg("ra") unsigned int val);
unsigned int _inp_25(void);
void _outp_25(__reg("ra") unsigned int val);
unsigned int _inp_26(void);
void _outp_26(__reg("ra") unsigned int val);
unsigned int _inp_27(void);
void _outp_27(__reg("ra") unsigned int val);
unsigned int _inp_28(void);
void _outp_28(__reg("ra") unsigned int val);
unsigned int _inp_29(void);
void _outp_29(__reg("ra") unsigned int val);
unsigned int _inp_30(void);
void _outp_30(__reg("ra") unsigned int val);
unsigned int _inp_31(void);
void _outp_31(__reg("ra") unsigned int val);
unsigned int _inp_32(void);
void _outp_32(__reg("ra") unsigned int val);
unsigned int _inp_33(void);
void _outp_33(__reg("ra") unsigned int val);
unsigned int _inp_34(void);
void _outp_34(__reg("ra") unsigned int val);
unsigned int _inp_35(void);
void _outp_35(__reg("ra") unsigned int val);
unsigned int _inp_36(void);
void _outp_36(__reg("ra") unsigned int val);
unsigned int _inp_37(void);
void _outp_37(__reg("ra") unsigned int val);
unsigned int _inp_38(void);
void _outp_38(__reg("ra") unsigned int val);
unsigned int _inp_39(void);
void _outp_39(__reg("ra") unsigned int val);
unsigned int _inp_40(void);
void _outp_40(__reg("ra") unsigned int val);
unsigned int _inp_41(void);
void _outp_41(__reg("ra") unsigned int val);
unsigned int _inp_42(void);
void _outp_42(__reg("ra") unsigned int val);
unsigned int _inp_43(void);
void _outp_43(__reg("ra") unsigned int val);
unsigned int _inp_44(void);
void _outp_44(__reg("ra") unsigned int val);
unsigned int _inp_45(void);
void _outp_45(__reg("ra") unsigned int val);
unsigned int _inp_46(void);
void _outp_46(__reg("ra") unsigned int val);
unsigned int _inp_47(void);
void _outp_47(__reg("ra") unsigned int val);
unsigned int _inp_48(void);
void _outp_48(__reg("ra") unsigned int val);
unsigned int _inp_49(void);
void _outp_49(__reg("ra") unsigned int val);
unsigned int _inp_50(void);
void _outp_50(__reg("ra") unsigned int val);
unsigned int _inp_51(void);
void _outp_51(__reg("ra") unsigned int val);
unsigned int _inp_52(void);
void _outp_52(__reg("ra") unsigned int val);
unsigned int _inp_53(void);
void _outp_53(__reg("ra") unsigned int val);
unsigned int _inp_54(void);
void _outp_54(__reg("ra") unsigned int val);
unsigned int _inp_55(void);
void _outp_55(__reg("ra") unsigned int val);
unsigned int _inp_56(void);
void _outp_56(__reg("ra") unsigned int val);
unsigned int _inp_57(void);
void _outp_57(__reg("ra") unsigned int val);
unsigned int _inp_58(void);
void _outp_58(__reg("ra") unsigned int val);
unsigned int _inp_59(void);
void _outp_59(__reg("ra") unsigned int val);
unsigned int _inp_60(void);
void _outp_60(__reg("ra") unsigned int val);
unsigned int _inp_61(void);
void _outp_61(__reg("ra") unsigned int val);
unsigned int _inp_62(void);
void _outp_62(__reg("ra") unsigned int val);
unsigned int _inp_63(void);
void _outp_63(__reg("ra") unsigned int val);
unsigned int _inp_64(void);
void _outp_64(__reg("ra") unsigned int val);
unsigned int _inp_65(void);
void _outp_65(__reg("ra") unsigned int val);
unsigned int _inp_66(void);
void _outp_66(__reg("ra") unsigned int val);
unsigned int _inp_67(void);
void _outp_67(__reg("ra") unsigned int val);
unsigned int _inp_68(void);
void _outp_68(__reg("ra") unsigned int val);
unsigned int _inp_69(void);
void _outp_69(__reg("ra") unsigned int val);
unsigned int _inp_70(void);
void _outp_70(__reg("ra") unsigned int val);
unsigned int _inp_71(void);
void _outp_71(__reg("ra") unsigned int val);
unsigned int _inp_72(void);
void _outp_72(__reg("ra") unsigned int val);
unsigned int _inp_73(void);
void _outp_73(__reg("ra") unsigned int val);
unsigned int _inp_74(void);
void _outp_74(__reg("ra") unsigned int val);
unsigned int _inp_75(void);
void _outp_75(__reg("ra") unsigned int val);
unsigned int _inp_76(void);
void _outp_76(__reg("ra") unsigned int val);
unsigned int _inp_77(void);
void _outp_77(__reg("ra") unsigned int val);
unsigned int _inp_78(void);
void _outp_78(__reg("ra") unsigned int val);
unsigned int _inp_79(void);
void _outp_79(__reg("ra") unsigned int val);
unsigned int _inp_80(void);
void _outp_80(__reg("ra") unsigned int val);
unsigned int _inp_81(void);
void _outp_81(__reg("ra") unsigned int val);
unsigned int _inp_82(void);
void _outp_82(__reg("ra") unsigned int val);
unsigned int _inp_83(void);
void _outp_83(__reg("ra") unsigned int val);
unsigned int _inp_84(void);
void _outp_84(__reg("ra") unsigned int val);
unsigned int _inp_85(void);
void _outp_85(__reg("ra") unsigned int val);
unsigned int _inp_86(void);
void _outp_86(__reg("ra") unsigned int val);
unsigned int _inp_87(void);
void _outp_87(__reg("ra") unsigned int val);
unsigned int _inp_88(void);
void _outp_88(__reg("ra") unsigned int val);
unsigned int _inp_89(void);
void _outp_89(__reg("ra") unsigned int val);
unsigned int _inp_90(void);
void _outp_90(__reg("ra") unsigned int val);
unsigned int _inp_91(void);
void _outp_91(__reg("ra") unsigned int val);
unsigned int _inp_92(void);
void _outp_92(__reg("ra") unsigned int val);
unsigned int _inp_93(void);
void _outp_93(__reg("ra") unsigned int val);
unsigned int _inp_94(void);
void _outp_94(__reg("ra") unsigned int val);
unsigned int _inp_95(void);
void _outp_95(__reg("ra") unsigned int val);
unsigned int _inp_96(void);
void _outp_96(__reg("ra") unsigned int val);
unsigned int _inp_97(void);
void _outp_97(__reg("ra") unsigned int val);
unsigned int _inp_98(void);
void _outp_98(__reg("ra") unsigned int val);
unsigned int _inp_99(void);
void _outp_99(__reg("ra") unsigned int val);
unsigned int _inp_100(void);
void _outp_100(__reg("ra") unsigned int val);
unsigned int _inp_101(void);
void _outp_101(__reg("ra") unsigned int val);
unsigned int _inp_102(void);
void _outp_102(__reg("ra") unsigned int val);
unsigned int _inp_103(void);
void _outp_103(__reg("ra") unsigned int val);
unsigned int _inp_104(void);
void _outp_104(__reg("ra") unsigned int val);
unsigned int _inp_105(void);
void _outp_105(__reg("ra") unsigned int val);
unsigned int _inp_106(void);
void _outp_106(__reg("ra") unsigned int val);
unsigned int _inp_107(void);
void _outp_107(__reg("ra") unsigned int val);
unsigned int _inp_108(void);
void _outp_108(__reg("ra") unsigned int val);
unsigned int _inp_109(void);
void _outp_109(__reg("ra") unsigned int val);
unsigned int _inp_110(void);
void _outp_110(__reg("ra") unsigned int val);
unsigned int _inp_111(void);
void _outp_111(__reg("ra") unsigned int val);
unsigned int _inp_112(void);
void _outp_112(__reg("ra") unsigned int val);
unsigned int _inp_113(void);
void _outp_113(__reg("ra") unsigned int val);
unsigned int _inp_114(void);
void _outp_114(__reg("ra") unsigned int val);
unsigned int _inp_115(void);
void _outp_115(__reg("ra") unsigned int val);
unsigned int _inp_116(void);
void _outp_116(__reg("ra") unsigned int val);
unsigned int _inp_117(void);
void _outp_117(__reg("ra") unsigned int val);
unsigned int _inp_118(void);
void _outp_118(__reg("ra") unsigned int val);
unsigned int _inp_119(void);
void _outp_119(__reg("ra") unsigned int val);
unsigned int _inp_120(void);
void _outp_120(__reg("ra") unsigned int val);
unsigned int _inp_121(void);
void _outp_121(__reg("ra") unsigned int val);
unsigned int _inp_122(void);
void _outp_122(__reg("ra") unsigned int val);
unsigned int _inp_123(void);
void _outp_123(__reg("ra") unsigned int val);
unsigned int _inp_124(void);
void _outp_124(__reg("ra") unsigned int val);
unsigned int _inp_125(void);
void _outp_125(__reg("ra") unsigned int val);
unsigned int _inp_126(void);
void _outp_126(__reg("ra") unsigned int val);
unsigned int _inp_127(void);
void _outp_127(__reg("ra") unsigned int val);
unsigned int _inp_128(void);
void _outp_128(__reg("ra") unsigned int val);
unsigned int _inp_129(void);
void _outp_129(__reg("ra") unsigned int val);
unsigned int _inp_130(void);
void _outp_130(__reg("ra") unsigned int val);
unsigned int _inp_131(void);
void _outp_131(__reg("ra") unsigned int val);
unsigned int _inp_132(void);
void _outp_132(__reg("ra") unsigned int val);
unsigned int _inp_133(void);
void _outp_133(__reg("ra") unsigned int val);
unsigned int _inp_134(void);
void _outp_134(__reg("ra") unsigned int val);
unsigned int _inp_135(void);
void _outp_135(__reg("ra") unsigned int val);
unsigned int _inp_136(void);
void _outp_136(__reg("ra") unsigned int val);
unsigned int _inp_137(void);
void _outp_137(__reg("ra") unsigned int val);
unsigned int _inp_138(void);
void _outp_138(__reg("ra") unsigned int val);
unsigned int _inp_139(void);
void _outp_139(__reg("ra") unsigned int val);
unsigned int _inp_140(void);
void _outp_140(__reg("ra") unsigned int val);
unsigned int _inp_141(void);
void _outp_141(__reg("ra") unsigned int val);
unsigned int _inp_142(void);
void _outp_142(__reg("ra") unsigned int val);
unsigned int _inp_143(void);
void _outp_143(__reg("ra") unsigned int val);
unsigned int _inp_144(void);
void _outp_144(__reg("ra") unsigned int val);
unsigned int _inp_145(void);
void _outp_145(__reg("ra") unsigned int val);
unsigned int _inp_146(void);
void _outp_146(__reg("ra") unsigned int val);
unsigned int _inp_147(void);
void _outp_147(__reg("ra") unsigned int val);
unsigned int _inp_148(void);
void _outp_148(__reg("ra") unsigned int val);
unsigned int _inp_149(void);
void _outp_149(__reg("ra") unsigned int val);
unsigned int _inp_150(void);
void _outp_150(__reg("ra") unsigned int val);
unsigned int _inp_151(void);
void _outp_151(__reg("ra") unsigned int val);
unsigned int _inp_152(void);
void _outp_152(__reg("ra") unsigned int val);
unsigned int _inp_153(void);
void _outp_153(__reg("ra") unsigned int val);
unsigned int _inp_154(void);
void _outp_154(__reg("ra") unsigned int val);
unsigned int _inp_155(void);
void _outp_155(__reg("ra") unsigned int val);
unsigned int _inp_156(void);
void _outp_156(__reg("ra") unsigned int val);
unsigned int _inp_157(void);
void _outp_157(__reg("ra") unsigned int val);
unsigned int _inp_158(void);
void _outp_158(__reg("ra") unsigned int val);
unsigned int _inp_159(void);
void _outp_159(__reg("ra") unsigned int val);
unsigned int _inp_160(void);
void _outp_160(__reg("ra") unsigned int val);
unsigned int _inp_161(void);
void _outp_161(__reg("ra") unsigned int val);
unsigned int _inp_162(void);
void _outp_162(__reg("ra") unsigned int val);
unsigned int _inp_163(void);
void _outp_163(__reg("ra") unsigned int val);
unsigned int _inp_164(void);
void _outp_164(__reg("ra") unsigned int val);
unsigned int _inp_165(void);
void _outp_165(__reg("ra") unsigned int val);
unsigned int _inp_166(void);
void _outp_166(__reg("ra") unsigned int val);
unsigned int _inp_167(void);
void _outp_167(__reg("ra") unsigned int val);
unsigned int _inp_168(void);
void _outp_168(__reg("ra") unsigned int val);
unsigned int _inp_169(void);
void _outp_169(__reg("ra") unsigned int val);
unsigned int _inp_170(void);
void _outp_170(__reg("ra") unsigned int val);
unsigned int _inp_171(void);
void _outp_171(__reg("ra") unsigned int val);
unsigned int _inp_172(void);
void _outp_172(__reg("ra") unsigned int val);
unsigned int _inp_173(void);
void _outp_173(__reg("ra") unsigned int val);
unsigned int _inp_174(void);
void _outp_174(__reg("ra") unsigned int val);
unsigned int _inp_175(void);
void _outp_175(__reg("ra") unsigned int val);
unsigned int _inp_176(void);
void _outp_176(__reg("ra") unsigned int val);
unsigned int _inp_177(void);
void _outp_177(__reg("ra") unsigned int val);
unsigned int _inp_178(void);
void _outp_178(__reg("ra") unsigned int val);
unsigned int _inp_179(void);
void _outp_179(__reg("ra") unsigned int val);
unsigned int _inp_180(void);
void _outp_180(__reg("ra") unsigned int val);
unsigned int _inp_181(void);
void _outp_181(__reg("ra") unsigned int val);
unsigned int _inp_182(void);
void _outp_182(__reg("ra") unsigned int val);
unsigned int _inp_183(void);
void _outp_183(__reg("ra") unsigned int val);
unsigned int _inp_184(void);
void _outp_184(__reg("ra") unsigned int val);
unsigned int _inp_185(void);
void _outp_185(__reg("ra") unsigned int val);
unsigned int _inp_186(void);
void _outp_186(__reg("ra") unsigned int val);
unsigned int _inp_187(void);
void _outp_187(__reg("ra") unsigned int val);
unsigned int _inp_188(void);
void _outp_188(__reg("ra") unsigned int val);
unsigned int _inp_189(void);
void _outp_189(__reg("ra") unsigned int val);
unsigned int _inp_190(void);
void _outp_190(__reg("ra") unsigned int val);
unsigned int _inp_191(void);
void _outp_191(__reg("ra") unsigned int val);
unsigned int _inp_192(void);
void _outp_192(__reg("ra") unsigned int val);
unsigned int _inp_193(void);
void _outp_193(__reg("ra") unsigned int val);
unsigned int _inp_194(void);
void _outp_194(__reg("ra") unsigned int val);
unsigned int _inp_195(void);
void _outp_195(__reg("ra") unsigned int val);
unsigned int _inp_196(void);
void _outp_196(__reg("ra") unsigned int val);
unsigned int _inp_197(void);
void _outp_197(__reg("ra") unsigned int val);
unsigned int _inp_198(void);
void _outp_198(__reg("ra") unsigned int val);
unsigned int _inp_199(void);
void _outp_199(__reg("ra") unsigned int val);
unsigned int _inp_200(void);
void _outp_200(__reg("ra") unsigned int val);
unsigned int _inp_201(void);
void _outp_201(__reg("ra") unsigned int val);
unsigned int _inp_202(void);
void _outp_202(__reg("ra") unsigned int val);
unsigned int _inp_203(void);
void _outp_203(__reg("ra") unsigned int val);
unsigned int _inp_204(void);
void _outp_204(__reg("ra") unsigned int val);
unsigned int _inp_205(void);
void _outp_205(__reg("ra") unsigned int val);
unsigned int _inp_206(void);
void _outp_206(__reg("ra") unsigned int val);
unsigned int _inp_207(void);
void _outp_207(__reg("ra") unsigned int val);
unsigned int _inp_208(void);
void _outp_208(__reg("ra") unsigned int val);
unsigned int _inp_209(void);
void _outp_209(__reg("ra") unsigned int val);
unsigned int _inp_210(void);
void _outp_210(__reg("ra") unsigned int val);
unsigned int _inp_211(void);
void _outp_211(__reg("ra") unsigned int val);
unsigned int _inp_212(void);
void _outp_212(__reg("ra") unsigned int val);
unsigned int _inp_213(void);
void _outp_213(__reg("ra") unsigned int val);
unsigned int _inp_214(void);
void _outp_214(__reg("ra") unsigned int val);
unsigned int _inp_215(void);
void _outp_215(__reg("ra") unsigned int val);
unsigned int _inp_216(void);
void _outp_216(__reg("ra") unsigned int val);
unsigned int _inp_217(void);
void _outp_217(__reg("ra") unsigned int val);
unsigned int _inp_218(void);
void _outp_218(__reg("ra") unsigned int val);
unsigned int _inp_219(void);
void _outp_219(__reg("ra") unsigned int val);
unsigned int _inp_220(void);
void _outp_220(__reg("ra") unsigned int val);
unsigned int _inp_221(void);
void _outp_221(__reg("ra") unsigned int val);
unsigned int _inp_222(void);
void _outp_222(__reg("ra") unsigned int val);
unsigned int _inp_223(void);
void _outp_223(__reg("ra") unsigned int val);
unsigned int _inp_224(void);
void _outp_224(__reg("ra") unsigned int val);
unsigned int _inp_225(void);
void _outp_225(__reg("ra") unsigned int val);
unsigned int _inp_226(void);
void _outp_226(__reg("ra") unsigned int val);
unsigned int _inp_227(void);
void _outp_227(__reg("ra") unsigned int val);
unsigned int _inp_228(void);
void _outp_228(__reg("ra") unsigned int val);
unsigned int _inp_229(void);
void _outp_229(__reg("ra") unsigned int val);
unsigned int _inp_230(void);
void _outp_230(__reg("ra") unsigned int val);
unsigned int _inp_231(void);
void _outp_231(__reg("ra") unsigned int val);
unsigned int _inp_232(void);
void _outp_232(__reg("ra") unsigned int val);
unsigned int _inp_233(void);
void _outp_233(__reg("ra") unsigned int val);
unsigned int _inp_234(void);
void _outp_234(__reg("ra") unsigned int val);
unsigned int _inp_235(void);
void _outp_235(__reg("ra") unsigned int val);
unsigned int _inp_236(void);
void _outp_236(__reg("ra") unsigned int val);
unsigned int _inp_237(void);
void _outp_237(__reg("ra") unsigned int val);
unsigned int _inp_238(void);
void _outp_238(__reg("ra") unsigned int val);
unsigned int _inp_239(void);
void _outp_239(__reg("ra") unsigned int val);
unsigned int _inp_240(void);
void _outp_240(__reg("ra") unsigned int val);
unsigned int _inp_241(void);
void _outp_241(__reg("ra") unsigned int val);
unsigned int _inp_242(void);
void _outp_242(__reg("ra") unsigned int val);
unsigned int _inp_243(void);
void _outp_243(__reg("ra") unsigned int val);
unsigned int _inp_244(void);
void _outp_244(__reg("ra") unsigned int val);
unsigned int _inp_245(void);
void _outp_245(__reg("ra") unsigned int val);
unsigned int _inp_246(void);
void _outp_246(__reg("ra") unsigned int val);
unsigned int _inp_247(void);
void _outp_247(__reg("ra") unsigned int val);
unsigned int _inp_248(void);
void _outp_248(__reg("ra") unsigned int val);
unsigned int _inp_249(void);
void _outp_249(__reg("ra") unsigned int val);
unsigned int _inp__sys_info_emulated(void);
unsigned int _inp_250(void);
void _outp__sys_info_emulated(__reg("ra") unsigned int val);
void _outp_250(__reg("ra") unsigned int val);
unsigned int _inp__sys_info_cpu_speed(void);
unsigned int _inp_251(void);
void _outp__sys_info_cpu_speed(__reg("ra") unsigned int val);
void _outp_251(__reg("ra") unsigned int val);
unsigned int _inp__sys_info_pages_mem(void);
unsigned int _inp_252(void);
void _outp__sys_info_pages_mem(__reg("ra") unsigned int val);
void _outp_252(__reg("ra") unsigned int val);
unsigned int _inp__sys_clock_in_port_low(void);
unsigned int _inp_253(void);
void _outp__sys_clock_in_port_low(__reg("ra") unsigned int val);
void _outp_253(__reg("ra") unsigned int val);
unsigned int _inp__sys_clock_in_port_high(void);
unsigned int _inp_254(void);
void _outp__sys_clock_in_port_high(__reg("ra") unsigned int val);
void _outp_254(__reg("ra") unsigned int val);
unsigned int _inp__int_timer_port(void);
unsigned int _inp_255(void);
void _outp__int_timer_port(__reg("ra") unsigned int val);
void _outp_255(__reg("ra") unsigned int val);
