unsigned int _inp__serial_data_in_port(void);
unsigned int _inp__serial_next_port(void);
unsigned int _inp_1(void);
void _outp__serial_data_in_port(__reg("ra") unsigned int val);
void _outp__serial_next_port(__reg("ra") unsigned int val);
void _outp_1(__reg("ra") unsigned int val);
unsigned int _inp__serial_in_waiting_port(void);
unsigned int _inp_2(void);
void _outp__serial_in_waiting_port(__reg("ra") unsigned int val);
void _outp_2(__reg("ra") unsigned int val);
unsigned int _inp__serial_data_out_port(void);
unsigned int _inp_3(void);
void _outp__serial_data_out_port(__reg("ra") unsigned int val);
void _outp_3(__reg("ra") unsigned int val);
unsigned int _inp__serial_tx_busy_port(void);
unsigned int _inp_4(void);
void _outp__serial_tx_busy_port(__reg("ra") unsigned int val);
void _outp_4(__reg("ra") unsigned int val);
unsigned int _inp__text_addr_port(void);
unsigned int _inp_5(void);
void _outp__text_addr_port(__reg("ra") unsigned int val);
void _outp_5(__reg("ra") unsigned int val);
unsigned int _inp__text_data_port(void);
unsigned int _inp_6(void);
void _outp__text_data_port(__reg("ra") unsigned int val);
void _outp_6(__reg("ra") unsigned int val);
unsigned int _inp__key_data_in_port(void);
unsigned int _inp__key_next_port(void);
unsigned int _inp_7(void);
void _outp__key_data_in_port(__reg("ra") unsigned int val);
void _outp__key_next_port(__reg("ra") unsigned int val);
void _outp_7(__reg("ra") unsigned int val);
unsigned int _inp__key_in_waiting_port(void);
unsigned int _inp_8(void);
void _outp__key_in_waiting_port(__reg("ra") unsigned int val);
void _outp_8(__reg("ra") unsigned int val);
unsigned int _inp__gfx_addr_port(void);
unsigned int _inp_9(void);
void _outp__gfx_addr_port(__reg("ra") unsigned int val);
void _outp_9(__reg("ra") unsigned int val);
unsigned int _inp__gfx_data_port(void);
unsigned int _inp_10(void);
void _outp__gfx_data_port(__reg("ra") unsigned int val);
void _outp_10(__reg("ra") unsigned int val);
unsigned int _inp__sound_freq_port(void);
unsigned int _inp_11(void);
void _outp__sound_freq_port(__reg("ra") unsigned int val);
void _outp_11(__reg("ra") unsigned int val);
unsigned int _inp__gfx_screen_en_port(void);
unsigned int _inp_12(void);
void _outp__gfx_screen_en_port(__reg("ra") unsigned int val);
void _outp_12(__reg("ra") unsigned int val);
unsigned int _inp__disk_busy_port(void);
unsigned int _inp__disk_reset_port(void);
unsigned int _inp_13(void);
void _outp__disk_busy_port(__reg("ra") unsigned int val);
void _outp__disk_reset_port(__reg("ra") unsigned int val);
void _outp_13(__reg("ra") unsigned int val);
unsigned int _inp__disk_error_port(void);
unsigned int _inp__disk_block_addr_port(void);
unsigned int _inp_14(void);
void _outp__disk_error_port(__reg("ra") unsigned int val);
void _outp__disk_block_addr_port(__reg("ra") unsigned int val);
void _outp_14(__reg("ra") unsigned int val);
unsigned int _inp__disk_data_in_port(void);
unsigned int _inp__disk_data_in_next_port(void);
unsigned int _inp_15(void);
void _outp__disk_data_in_port(__reg("ra") unsigned int val);
void _outp__disk_data_in_next_port(__reg("ra") unsigned int val);
void _outp_15(__reg("ra") unsigned int val);
unsigned int _inp__disk_data_in_rd_en_port(void);
unsigned int _inp__disk_data_in_addr_port(void);
unsigned int _inp_16(void);
void _outp__disk_data_in_rd_en_port(__reg("ra") unsigned int val);
void _outp__disk_data_in_addr_port(__reg("ra") unsigned int val);
void _outp_16(__reg("ra") unsigned int val);
unsigned int _inp__disk_data_out_port(void);
unsigned int _inp_17(void);
void _outp__disk_data_out_port(__reg("ra") unsigned int val);
void _outp_17(__reg("ra") unsigned int val);
unsigned int _inp__disk_data_out_wr_en_port(void);
unsigned int _inp__disk_data_out_addr_port(void);
unsigned int _inp_18(void);
void _outp__disk_data_out_wr_en_port(__reg("ra") unsigned int val);
void _outp__disk_data_out_addr_port(__reg("ra") unsigned int val);
void _outp_18(__reg("ra") unsigned int val);
unsigned int _inp__int_timer_port(void);
unsigned int _inp_255(void);
void _outp__int_timer_port(__reg("ra") unsigned int val);
void _outp_255(__reg("ra") unsigned int val);
