/* This file was automatically generated.  Do not edit! */
int main(int argc,char **argv);
void print_usage();
void run(FILE *out,char *fs_path);
uint16_t recurse_host_fs(char *host_path,FILE *out,ino_t host_inum,uint16_t disk_parent_inum);
uint8_t scp_test_dev(char *name,uint16_t *dev_major,uint16_t *dev_minor);
char *scp_file_get_real_name(char *name);
uint8_t is_scp_file_dont_include(char *name);
void expand_disk(FILE *out);
void write_0_1_inodes(FILE *out);
void write_file_to_disk(struct host_inode *inode,FILE *out,FILE *in);
void write_inodes(FILE *out);
void write_inode_to_disk(struct host_inode *inode,FILE *out);
struct host_inode *create_host_inode(uint8_t is_dir,uint8_t is_exec,uint8_t is_dev,uint16_t dev_major,uint16_t dev_minor,size_t file_size,ino_t host_inum,char *host_path);
struct host_inode *find_by_inum(ino_t inum);
struct host_inode *new_host_inode();
extern size_t disk_inode_index;
extern size_t host_inodes_index;
extern size_t host_inodes_size;
extern struct host_inode *host_inodes;
void write_superblock(FILE *out);
void init_superblk(uint16_t boot_img_present);
extern struct superblock superblk;
void write_os_image(FILE *out,FILE *img);
uint16_t *alloc_blocks(size_t n);
void write_block_ll(FILE *out);
void init_block_ll();
void write_bytes(FILE *out,uint8_t *bytes,size_t size);
void write_word(FILE *out,uint16_t word);
void write_byte(FILE *out,uint8_t byte);
extern uint32_t block_ll_index;
extern uint16_t block_ll[DISK_NUM_BLKS];
